name: e_pkk
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.20
 
  dropdown_button2: ^2.0.0
  file_picker: ^5.2.9
 
  cherry_toast: ^1.2.1
  fluttertoast: ^8.2.1
  google_nav_bar: ^5.0.6
  awesome_dialog: ^3.0.2
  searchfield: ^0.7.5
  # dropdownfield: ^1.0.0
  simple_shadow: ^0.2.0
  intl: ^0.18.1
  # substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
