name: e_pkk
description: Aplikasi E-PKK dibuat untuk mempermudah kader pkk dalam aktivitasnya.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.20
  fluttertoast: ^8.2.1
  google_nav_bar: ^5.0.6
  awesome_dialog: ^3.0.2
  searchfield: ^0.8.4
  carousel_slider: ^4.2.1
  lottie: ^2.3.2
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.1.2
  cherry_toast: ^1.2.1
  file_picker: ^5.3.0
  simple_shadow: ^0.3.1
  intl: ^0.18.1
  shimmer: ^3.0.0
  awesome_notifications: ^0.6.19
  # flutter_native_splash: ^2.2.19

  # dropdown_button2: ^2.0.0
  # substring_highlight: ^1.0.33
  # file_picker: ^5.2.9
  # cherry_toast: ^1.2.1
  # intl: ^0.18.
  # dropdownfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/images/pkk.png
#   android: true
#   ios: true
#   web: true

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
