name: e_pkk
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.20
  fluttertoast: ^8.2.1
  # flutter_svg: ^0.22.0
  # simple_shadow: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
